export var suggestions = [
    {name: "YouTube",
    url:"youtube.com",
    image:"https://www.youtube.com/yts/img/yt_1200-vflhSIVnY.png"},
    {name: "Google",
    url: "google.com",
    image: "https://cdn4.iconfinder.com/data/icons/bettericons/354/google-2-color-512.png"},
    {name: "Wells Fargo",
    url: "wellsfargo.com",
    image:"https://upload.wikimedia.org/wikipedia/commons/c/c9/Wells_Fargo_Logo_%282020%29.png" },
    {name: "Bank of America",
    url: "bankofamerica.com",
    image:"https://lh3.googleusercontent.com/GdICLxnKd-e-lmV46N_SjihWHzAUX1nj8e--dF2KrQjvomN4zxOR-iEWwsTG_Tqr_oc" },
    {name: "Wikipedia",
    url: "wikipedia.org",
    image:"https://upload.wikimedia.org/wikipedia/en/thumb/8/80/Wikipedia-logo-v2.svg/1200px-Wikipedia-logo-v2.svg.png"},
    {name: "Twitter",
    url: "twitter.com",
    image:"https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/c5/5e/26/c55e261f-607f-ee4b-7466-19fc14d87968/ProductionAppIcon-0-0-1x_U007emarketing-0-0-0-7-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/246x0w.png"}, 
    {name: "Facebook",
    url: "facebook.com", 
    image: "https://www.facebook.com/images/fb_icon_325x325.png"},
    {name: "Amazon",
    url: "amazon.com", 
    image: "https://images-na.ssl-images-amazon.com/images/I/51J6cQ63OJL._SY355_.png"},
    {name: "Yelp",
    url: "yelp.com",
    image:"https://www.scottsdaleeye.com/wp-content/uploads/2015/10/yelp-icon.png"},
    {name: "Reddit",
    url: "reddit.com",
    image: "https://www.redditinc.com/assets/images/site/reddit-logo.png"},
    {name: "IMDb",
    url: "imdb.com",
    image: "https://pbs.twimg.com/profile_images/976507090624589824/0x28al44_400x400.jpg"},
    {name: "Fandom",
    url: "fandom.com",
    image: "https://www.pngkit.com/png/full/20-205143_fandom-heart-icon-fandom-logo.png"},
    {name: "Pinterest",
    url: "pinterest.com",
    image:"https://i.pinimg.com/236x/81/54/9c/81549c00e708172661c8233244b8f28f--business-tips-business-marketing.jpg"},
    {name: "Trip Advisor",
    url: "tripadvisor.com",
    image:"https://cdn3.iconfinder.com/data/icons/popular-services-brands-vol-2/512/tripadvisor-512.png"},
    {name: "Instagram",
    url: "instagram.com",
    image:"https://cdn-images-1.medium.com/max/1200/1*CPgwLHR6jno_tOmF0--7eg.jpeg"},
    {name: "Walmart",
    url: "walmart.com",
    image: "https://www.bocaratontribune.com/wp-content/uploads/2020/06/walmart-logo.jpg"},
    {name: "Craigslist",
    url: "craigslist.org",
    image:"https://www.coachcarson.com/wp-content/uploads/2017/05/Craigslist-Peace-Sign-Logo.jpg"},
    {name: "eBay",
    url: "ebay.com",
    image: "https://cdn.business2community.com/wp-content/uploads/2012/10/ebay_old_logo.jpg"},
    {name: "LinkedIn",
    url: "linkedin.com",
    image:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/LinkedIn_logo_initials.png/768px-LinkedIn_logo_initials.png"},
    {name: "Google Play",
    url: "play.google.com",
    image: "https://pbs.twimg.com/profile_images/890249520075898881/XwwbQj3q_400x400.jpg"},
    {name: "Healthline",
    url: "healthline.com",
    image: "https://www.clipartkey.com/mpngs/m/184-1845840_healthline-media-logo.png"},
    {name: "Etsy",
    url: "etsy.com",
    image: "https://bushelandpecks.com/wp-content/uploads/2017/03/etsy-logo.png"},
    {name: "Indeed",
    url: "indeed.com",
    image:"https://www.logolynx.com/images/logolynx/98/98bd7c22237938ad25adcafcabe5b5a8.png"},
    {name: "Apple",
    url: "apple.com",
    image:"https://media.idownloadblog.com/wp-content/uploads/2018/07/Apple-logo-black-and-white.png"},
    {name: "ESPN",
    url: "espn.com",
    image: "https://cdn.theorg.com/9ef7b6c0-b95c-44b2-9a62-cb2996442035_medium.jpg"},
    {name: "WebMD",
    url: "webmd.com",
    image: "https://d3bffa21w6ew09.cloudfront.net/servicelogo/webmd_logo.png"},
    {name: "NYTimes",
    url: "nytimes.com",
    image:"https://pbs.twimg.com/profile_images/1098244578472280064/gjkVMelR_400x400.png"},
    {name: "CNN",
    url: "cnn.com",
    image: "https://i.pinimg.com/originals/61/2c/51/612c51731d3cebfd8be6dc76c5350e87.jpg"},
    {name: "Merriam Webster",
    url: "merriam-webster.com",
    image:"https://merriam-webster.com/assets/mw/static/social-media-share/mw-logo-245x245@1x.png"},
    {name: "Gamepedia",
    url: "gamepedia.com",
    image:"https://pbs.twimg.com/profile_images/512259402133274624/9XpsY35m_400x400.png"},
    {name: "Microsoft",
    url: "microsoft.com",
    image:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo.svg/1024px-Microsoft_logo.svg.png"},
    {name: "Target",
    url: "target.com",
    image:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Target_Corporation_logo_%28vector%29.svg/1200px-Target_Corporation_logo_%28vector%29.svg.png"},
    {name: "Home Depot",
    url: "homedepot.com",
    image:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/TheHomeDepot.svg/1020px-TheHomeDepot.svg.png"},
    {name: "Quora",
    url: "quora.com",
    image:"https://images.vexels.com/media/users/3/137401/isolated/preview/00300d00be87848b87d820f2664bc7eb-quora-icon-logo-by-vexels.png"},
    {name: "NIH",
    url: "nih.gov",
    image: "https://www.nih.gov/sites/default/files/about-nih/2012-logo.png"},
    {name: "Rotten Tomatoes",
    url: "rottentomatoes.com",
    image: "https://www.thewrap.com/wp-content/uploads/2017/08/RottenTomatoes.jpg"},
    {name: "Netflix",
    url: "netflix.com",
    image:"https://cdn.vox-cdn.com/thumbor/AwKSiDyDnwy_qoVdLPyoRPUPo00=/39x0:3111x2048/1400x1400/filters:focal(39x0:3111x2048):format(png)/cdn.vox-cdn.com/uploads/chorus_image/image/49901753/netflixlogo.0.0.png"},
    {name: "Quizlet",
    url: "quizlet.com",
    image: "https://assets.quizlet.com/a/i/brandmark/1024.893fa7e00da6339.png"},
    {name: "Weather",
    url: "weather.com",
    image:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/The_Weather_Channel_logo_2005-present.svg/1200px-The_Weather_Channel_logo_2005-present.svg.png"},
    {name: "MapQuest",
    url: "mapquest.com",
    image:"https://p11cdn4static.sharpschool.com/UserFiles/Servers/Server_366799/Image/MapQuest-1.png"},
    {name: "Google Maps",
    url: "maps.google.com",
    image:"https://cdn.vox-cdn.com/thumbor/pOMbzDvdEWS8NIeUuhxp23wi_cU=/1400x1400/filters:format(png)/cdn.vox-cdn.com/uploads/chorus_asset/file/19700731/googlemaps.png"},
    {name: "Britannica",
    url: "britannica.com",
    image: "https://www.britannica.com/resources/images/EBLogo.jpg"},
    {name: "Business Insider",
    url: "businessinsider.com",
    image:"https://res-1.cloudinary.com/crunchbase-production/image/upload/c_lpad,f_auto,q_auto:eco/v1487971691/op5cpcljulrjqwsiig6f.png"},
    {name: "Dictionary",
    url: "dictionary.com",
    image: "https://pbs.twimg.com/profile_images/654054329641340928/rtW_EGnL_400x400.png"},
    {name: "Ziilow",
    url: "zillow.com",
    image: "https://images-na.ssl-images-amazon.com/images/I/41RuzHh8MML.png"},
    {name: "Mayo Clinic",
    url: "mayoclinic.org",
    image:"https://mediad.publicbroadcasting.net/p/wjct/files/styles/small/public/201311/mayo_clinic.jpg"},
    {name: "Best Buy",
    url: "bestbuy.com",
    image: "https://i.pinimg.com/280x280_RS/09/27/46/092746d104326df11cce96b62d2c6a8e.jpg"},
    {name: "The Guardian",
    url: "theguardian.com",
    image: "https://kahoot.com/files/2020/03/guardian-logo-square.jpg"},
    {name: "Yahoo!",
    url: "yahoo.com",
    image:"https://cdn.vox-cdn.com/thumbor/JiRzoaU535Vs9YjU6LcJSvIGFBs=/1400x1400/filters:format(jpeg)/cdn.vox-cdn.com/uploads/chorus_asset/file/19224216/mb_yahoo_02.jpg"},
    {name: "MSN",
    url: "msn.com",
    image: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Msn_logo.jpg"},
    {name: "USA Today",
    url: "usatoday.com",
    image: "https://images-eu.ssl-images-amazon.com/images/I/41Ff9EvTPfL.png"},
    {name: "Medical News Today",
    url: "medicalnewstoday.com",
    image: "https://i.pinimg.com/280x280_RS/4f/37/57/4f3757534fbad448d830a51436de9378.jpg"},
    {name: "Urban Dictionary",
    url: "urbandictionary.com",
    image:"https://pbs.twimg.com/profile_images/1149416858426081280/uvwDuyqS_400x400.png"},
    {name: "US News",
    url: "usnews.com",
    image:"https://res-4.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_256,w_256,f_auto,q_auto:eco/v1409995449/z8ijt3il3px96gfxkgbw.png"},
    {name: "Fox News",
    url: "foxnews.com",
    image:"https://d12jofbmgge65s.cloudfront.net/blog/wp-content/uploads/2019/04/Fox-news-logo.png"},
    {name: "Genius",
    url: "genius.com",
    image: "https://images.genius.com/69333b682fca131dfc5cc94d072ab2f9.750x750x1.png"},
    {name: "Allrecipes",
    url: "allrecipes.com",
    image: "https://pbs.twimg.com/profile_images/1219652767796645888/WhIEPP9c.jpg"},
    {name: "Spotify",
    url: "spotify.com",
    image: "https://www.scdn.co/i/_global/twitter_card-default.jpg"},
    {name: "Glassdoor",
    url: "glassdoor.com",
    image: "https://media.glassdoor.com/sqll/100431/glassdoor-squarelogo-1552618157617.png"},
    {name: "Forbes",
    url: "forbes.com",
    image:"https://thumbor.forbes.com/thumbor/filters%3Aformat%28jpg%29/https%3A%2F%2Fi.forbesimg.com%2Fmedia%2Fassets%2Fforbes_1200x1200.jpg"},
    {name: "CNET",
    url: "cnet.com",
    image: "https://tivoli-audio.fr/template_images/build/catalogue/modelone/cnet.png"},
    {name: "Yahoo! Finance",
    url: "finance.yahoo.com",
    image:"https://s.yimg.com/uu/api/res/1.2/6zrfdEufg6W_gUl8JMeznQ--~B/Zmk9c3RyaW07aD00MDA7dz00MDA7YXBwaWQ9eXRhY2h5b24-/https://media-mbst-pub-ue1.s3.amazonaws.com/creatr-uploaded-images/2019-09/1f16fbf0-de0a-11e9-9af9-77bfe97840a9.cf.jpg"},
    {name: "IRS",
    url: "irs.gov",
    image: "https://www.irs.gov/pub/image/logo_small.jpg"},
    {name: "Lowe’s",
    url: "lowes.com",
    image: "https://cdn.worldvectorlogo.com/logos/lowe-s-1.svg"},
    {name: "Yahoo! Mail",
    url: "mail.yahoo.com",
    image: "https://cdn.techmesto.com/wp-content/uploads/2017/12/yahoomail.png"},
    {name: "AOL",
    url: "aol.com",
    image:"https://marketingland.com/wp-content/ml-loads/2015/07/AOL-logo-1920-x-1080.jpg"},
    {name: "Steam",
    url: "store.steampowered.com",
    image: "https://i.pinimg.com/474x/32/a8/1a/32a81ac6068b7cf9a132cc150802d19a.jpg"},
    {name: "Washington Post",
    url: "washingtonpost.com",
    image:"https://media.glassdoor.com/sqll/1058/the-washington-post-squarelogo-1574698215042.png"},
    {name: "USPS",
    url: "usps.com",
    image:"https://www.logolynx.com/images/logolynx/ec/eca27f29301cfb3ece0afc3b0877060f.jpeg"},
    {name: "Office",
    url: "office.com",
    image:"https://msp2l1160225102310.blob.core.windows.net/ms-p2-l1-160225-1023-13-assets/school-leaders-office-275x275.png"},
    {name: "RetailMeNot",
    url: "retailmenot.com",
    image:"https://alternative.me/media/256/retailmenot-icon-99k89ur51epx3wnt-c.png"},
    {name: "Wiktionary",
    url: "wiktionary.org",
    image:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Wiktfavicon_en.svg/1024px-Wiktfavicon_en.svg.png"},
    {name: "Paypal",
    url: "paypal.com",
    image:"https://germanyfintech.org/wp-content/uploads/2017/10/paypal-logo-600x600.jpg"},
    {name: "BBB",
    url: "bbb.org",
    image: "https://www.bbb.org/TerminusContent/_shared/images/logo_square.png"},
    {name: "Food Network",
    url: "foodnetwork.com",
    image:"https://lh3.googleusercontent.com/PY4xIPd7xgwBC0kYxBivXOalF0slfVSi4s1Hlw6c-oqnc9vYtrNNZDaor_v_DZwXwlk=w257"},
    {name: "Hulu",
    url: "hulu.com",
    image:"https://d26oc3sg82pgk3.cloudfront.net/files/media/edit/image/4642/square_thumb%402x.png"},
    {name: "Fiverr",
    url: "fiverr.com",
    image: "https://1000logos.net/wp-content/uploads/2017/08/Fiverr-emblem.jpg"},
    {name: "Ultimate Guitar",
    url: "ultimate-guitar.com",
    image:"https://assets.materialup.com/uploads/01b974c1-4c5c-4332-88cc-42844c389cc7/0x0ss-85.jpg"},
    {name: "Songsterr",
    url: "songsterr.com",
    image: "https://images-na.ssl-images-amazon.com/images/I/518vXC1Y%2BuL.png"},
    {name: "Soundcloud",
    url: "soundcloud.com",
    image:"https://media.wired.com/photos/592718a9af95806129f519a8/master/pass/Soundcloud-icon-2.jpg"},
    {name: "TypeRacer",
    url: "play.typeracer.com",
    image: "https://upload.wikimedia.org/wikipedia/en/2/27/TypeRacer_game.png"},
    {name: "Twitch",
    url: "twitch.tv",
    image:"https://blog.twitch.tv/assets/uploads/03-glitch.jpg"},
    {name: "Outlook",
    url: "outlook.live.com",
    image:"https://cdn.iconscout.com/icon/free/png-512/microsoft-outlook-2-569268.png"},
    {name: "CBS Sports",
    url: "cbssports.com",
    image: "https://sports.cbsimg.net/images/cbss/ui5/cbssportsv2_200x200.png"},
    {name: "Wayfair",
    url: "wayfair.com",
    image:"https://media.glassdoor.com/sqll/134525/wayfair-squarelogo-1521643856627.png"},
    {name: "Bleacher Report",
    url: "bleacherreport.com",
    image: "https://static-assets.bleacherreport.net/img/br_630_height.png"},
    {name: "Macy’s",
    url: "macys.com",
    image: "https://pbs.twimg.com/profile_images/1203089756910800896/me5MH3ve_400x400.jpg"},
    {name: "AccuWeather",
    url: "accuweather.com",
    image: "https://www.recovery-android.com/images/apps/accuweather.png"},
    {name: "Xfinity",
    url: "xfinity.com",
    image:"https://putnamchamber.org/wp-content/uploads/2018/10/corporate_lgo-xfinity-r-final.jpg"},
    {name: "Disney GO",
    url: "go.com",
    image: "https://upload.wikimedia.org/wikipedia/en/b/b1/Go.com_logo.png"},
    {name: "Disney",
    url: "disney.com",
    image: "https://lumiere-a.akamaihd.net/v1/images/image_308e48ed.png"},
    {name: "TechRadar",
    url: "techradar.com",
    image: "https://seekvectorlogo.com/wp-content/uploads/2018/11/techradar-vector-logo.png"},
    {name: "Groupon",
    url: "groupon.com",
    image: "https://i.pinimg.com/originals/a9/ec/68/a9ec6886066c8f4998c029cb66a4abaf.jpg"},
    {name: "Investopedia",
    url: "investopedia.com",
    image:"https://www.investopedia.com/thmb/CIRzPDZE6ZuiX21iC5NDaCD7xgU=/2347x0/filters:no_upscale():max_bytes(150000):strip_icc()/inv-best-of-template-1-5c54764946e0fb00013a21a0-5c61814046e0fb0001587722.jpg"},
    {name: "Yellow Pages",
    url: "yellowpages.com",
    image:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Yp_lgt_s_rgb_pos.jpg/220px-Yp_lgt_s_rgb_pos.jpg"},
    {name: "Steam Community",
    url: "steamcommunity.com",
    image:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Steam_icon_logo.svg/512px-Steam_icon_logo.svg.png"},
    {name: "Chase",
    url: "chase.com",
    image: "https://i.pinimg.com/originals/70/4a/1e/704a1e534e8dc0138eee3ded449555d5.png"},
    {name: "NPR",
    url: "npr.org",
    image:"https://em.uw.edu/sites/em.uw.edu/files/npr-logo.png"},
    {name: "Apartments",
    url: "apartments.com",
    image:"https://washingtonreianetwork.com/wp-content/uploads/2019/01/Apartments_logo-1-square.jpg"},
    {name: "Roblox",
    url: "roblox.com",
    image:"https://i.pinimg.com/originals/35/23/29/352329cf90c9dbb890f857dd9293c8c2.jpg"},
    {name: "HuffPost",
    url: "huffpost.com",
    image: "https://newsroom.mattressfirm.com/wp-content/uploads/2018/11/Huffpost-logo.jpg"},
    {name: "Google Books",
    url: "books.google.com",
    image:"https://logodix.com/logo/1338312.png"},
    {name: "Expedia",
    url: "expedia.com",
    image:"https://lh3.googleusercontent.com/kkf2Siy556vDQE_iqF0rAfmtdnHSo75AjBpRIfvCIxMruZdfGeb24S1UFDvb4wTQESg"},
    {name: "wikiHow",
    url: "wikihow.com",
    image: "https://media.glassdoor.com/sqll/765315/wikihow-squarelogo-1517957336478.png"},
    {name: "IGN",
    url: "ign.com",
    image: "https://in.ign.com/s/ign/social_logo.png"},
    {name: "Wowhead",
    url: "wowhead.com",
    image:"https://wow.zamimg.com/images/logos/share-icon.png"},
    {name: "Fidelity",
    url: "fidelity.com",
    image:"https://www.explora.us/wp-content/uploads/2018/04/fidelity-sq-logo.jpg"},
    {name: "Vanguard",
    url: "vanguard.com",
    image:"https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/69/90/65/699065a7-3d62-a574-c90c-33467b67dfe7/AppIcon-0-0-1x_U007emarketing-0-0-0-7-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/320x0w.png"},
    {name: "E-Trade",
    url: "us.etrade.com",
    image: "https://cdn.thecollegeinvestor.com/wp-content/uploads/2016/04/etrade-review.png"},
    {name: "TD Ameritrade",
    url: "tdameritrade.com",
    image:"https://png.pngitem.com/pimgs/s/391-3917804_td-ameritrade-logo-td-bank-logo-small-hd.png"},
    {name: "Robinhood",
    url: "robinhood.com",
    image: "https://www.uscreditcardguide.com/wp-content/uploads/robinhood.png"},
    {name: "Charles Schwab",
    url: "schwab.com",
    image: "https://stockplanservices.schwab.com/spm/images/CS-logo-DIGITAL.jpg"},
    {name: "Merrill Edge",
    url: "merrilledge.com",
    image:"https://pbs.twimg.com/profile_images/1274287967578869760/Gm4CN0z-_400x400.png"},
    {name: "Market Watch",
    url: "marketwatch.com",
    image: "https://pbs.twimg.com/profile_images/705601245596090368/Z6xUOnRg_400x400.jpg"},
    {name: "Bloomberg",
    url: "bloomberg.com",
    image: "https://i.pinimg.com/originals/71/b5/70/71b5706762354172b7ba6ea184d3ef38.png"},
    {name: "CNBC",
    url: "cnbc.com",
    image:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/CNBC_logo.svg/1280px-CNBC_logo.svg.png"},
    {name: "NBC",
    url: "nbc.com",
    image:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/NBC_logo.svg/1039px-NBC_logo.svg.png"},
    {name: "Fool",
    url: "www.fool.com",
    image: "https://optimize.foolcdn.com/?url=https%3A%2F%2Fg.foolcdn.com%2Fmisc-assets/jester.png&w=400&op=resize"},
    {name: "Morningstar",
    url: "morningstar.com",
    image:"https://lh3.googleusercontent.com/proxy/oWkZrN9UOqE76bojcnOSdBhZu7Ye2L9-dR9d7qmOiyyGhNiPDY6YwY0dfTw29PckyTHKMr9EDr3-PBSChpYK0RIaPCWlKAHYPtMO2S3XjEPY8tkobIkf9NRR5VlYFWq2cLXx7xDRWdnH2do"},
    {name: "WSJ",
    url: "wsj.com",
    image: "https://www.wsj.com/fonts/WSJ_facebook.png"},
    {name: "Garmin",
    url: "garmin.com",
    image: "https://fontmeme.com/images/garmin-logo.jpg"},
    {name: "Whole Foods Market",
    url: "wholefoodsmarket.com",
    image:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Whole_Foods_Market_201x_logo.svg/1200px-Whole_Foods_Market_201x_logo.svg.png"},
    {name: "Trader Joe’s",
    url: "www.traderjoes.com",
    image: "https://d3hjzzsa8cr26l.cloudfront.net/bb6ef351-10f6-11e8-a56d-535a4e504290.jpg"},
    {name: "Uber",
    url: "uber.com",
    image:"https://pbs.twimg.com/profile_images/1045783102000230400/TPLLaqYR_400x400.jpg"},
    {name: "Lyft",
    url: "lyft.com",
    image: "https://pbs.twimg.com/profile_images/1063591416918552576/lg72DZIS_400x400.jpg"},
    {name: "Uber Eats",
    url: "ubereats.com",
    image:"https://images.ctfassets.net/thgitcagx3w4/1BreumtXMCAeJD1aoXaRjX/c1388b37b67aeb80f237a35e9c0581f3/Hero_Image-UELogo.jpg"},
    {name: "DoorDash",
    url: "doordash.com",
    image: "https://pbs.twimg.com/profile_images/953514920435318785/7_O-NkAM_400x400.jpg"},
    {name: "Grubhub",
    url: "grubhub.com",
    image: "https://mma.prnewswire.com/media/887026/GrubHub4_Logo.jpg"},
    {name: "Postmates",
    url: "postmates.com",
    image:"https://esportsobserver.com/wp-content/uploads/2018/07/postmates-e1532108976213.jpg"},
    {name: "Google Drive",
    url: "google.com/drive",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Google_Drive_logo.png/1200px-Google_Drive_logo.png"},
    {name: "Dropbox",
    url: "dropbox.com",
    image: "https://brandslogo.net/wp-content/uploads/2014/09/dropbox-logo.png"},
    {name: "TeamViewer",
    url: "teamviewer.com",
    image: "https://static.teamviewer.com/resources/2019/07/TeamViewer_Logo_512x512.png"},
    {name: "AWS",
    url: "aws.amazon.com",
    image: "https://voicefoundry.com/wp-content/uploads/2018/09/feature-aws.jpg"},
    {name: "Alibaba",
    url: "alibaba.com",
    image: "https://privatelabel.directory/wp-content/uploads/2017/02/alibaba.png"},
    {name: "IBM",
    url: "ibm.com",
    image:"https://bigeqcampaign.org/wp-content/uploads/2020/03/ibm_logo.png"},
    {name: "IBM Cloud",
    url: "ibm.com/cloud",
    image:"https://cdn.freelogovectors.net/wp-content/uploads/2020/02/ibm-cloud-logo.png"},
    {name: "Google Cloud",
    url: "cloud.google.com",
    image:"https://www.gstatic.com/devrel-devsite/prod/vc0d10ef7c6e8aac6c71e2a2051f66f30f3c99a4b52237746839ce4f1fae2b7b4/cloud/images/favicons/onecloud/apple-icon.png"},
    {name: "Azure",
    url: "azure.microsoft.com",
    image:"https://azurementor.files.wordpress.com/2017/10/azure-logo.jpg"},
    {name: "Kubernetes",
    url: "kubernetes.io",
    image:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Kubernetes_logo_without_workmark.svg/1200px-Kubernetes_logo_without_workmark.svg.png"},
    {name: "Adobe",
    url: "adobe.com",
    image: "https://i.pinimg.com/originals/4d/3c/df/4d3cdf398e946991aa7a3c5c4960f06c.jpg"},
    {name: "Shutterstock",
    url: "shutterstock.com",
    image: "https://cdn.freebiesupply.com/logos/thumbs/2x/shutterstock-logo.png"},
    {name: "Udemy",
    url: "udemy.com",
    image: "https://about.udemy.com/wp-content/uploads/2017/10/NewUlogo-large-1.png"},
    {name: "Coursera",
    url: "coursera.org",
    image:"https://pbs.twimg.com/profile_images/579039906804023296/RWDlntRx_400x400.jpeg"},
    {name: "Udacity",
    url: "udacity.com",
    image:"https://coursereport-s3-production.global.ssl.fastly.net/rich/rich_files/rich_files/5511/s300/udacity-logo.png"},
    {name: "LinkedIn Learning",
    url: "linkedin.com/learning",
    image:"https://techblogwriter.co.uk/wp-content/uploads/2019/06/LinkedIn-Learning.png"},
    {name: "Nike",
    url: "nike.com",
    image: "https://c.static-nike.com/a/images/w_1920,c_limit/bzl2wmsfh7kgdkufrrjq/image.jpg"},
    {name: "Adidas",
    url: "adidas.com",
    image: "https://njmarlins.com/wp-content/uploads/sites/692/2015/04/adidas-logo.jpg"},
    {name: "Under Armour",
    url: "underarmour.com",
    image: "https://www.aquaflorya.com/data/magazalar/2/logo.png"},
    {name: "Coinbase",
    url: "coinbase.com",
    image: "https://cdn-images-1.medium.com/max/1200/1*gBXfxLQiRiP5NycsMHPzKA.png"},
    {name: "Binance",
    url: "binance.com",
    image: "https://cryptologos.cc/logos/binance-coin-bnb-logo.png"},
    {name: "Kraken",
    url: "kraken.com",
    image:"https://media.glassdoor.com/sqll/938667/kraken-digital-asset-exchange-squarelogo-1548817676185.png"},
    {name: "Reebok",
    url: "reebok.com",
    image:"https://www.logotaglines.com/wp-content/uploads/2018/04/Reebok-new-logo.png"},
    {name: "Canvas",
    url: "canvas.net",
    image:"https://www.cjr1.org/cms/lib/MO01909814/Centricity/Domain/513/Canvas%20logo%20for%20website.png"},
    {name: "T-Mobile",
    url: "t-mobile.com",
    image:"https://www.t-mobile.com/content/dam/t-mobile/corporate/media-library/public/pictures/logos/T-Mobile%20logo%20single%20T%20magenta%20on%20white.png/jcr:content/renditions/cq5dam.thumbnail.319.319.png"},
    {name: "Sprint",
    url: "sprint.com",
    image: "https://sbia.sprint.com/SBIA/resources/images/Sprint_Logo.png"},
    {name: "Metro by T-Mobile",
    url: "metrobyt-mobile.com",
    image:"https://vignette.wikia.nocookie.net/logopedia/images/6/64/Metro_by_T-Mobile_symbol.svg/revision/latest/top-crop/width/220/height/220?cb=20181215234637"},
    {name: "AT&T",
    url: "att.com",
    image:"https://lh3.googleusercontent.com/proxy/Az47hDfKD5zIQLbXS4hCI9_CvCUf66gn5ithQdpSpL5RfS36pS05H2qqhFBbcYBFpvvDENvb6N23OxsLFxRJqCp-S0rzs69IhITrLdhKObn4r9I95g"},
    {name: "Lenarr",
    url: "lennar.com",
    image:"https://res-3.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_256,w_256,f_auto,q_auto:eco/v1478608823/qrxlcamg0hsaheye3j2a.png"},
    {name: "Accenture",
    url: "accenture.com/us-en",
    image:"https://media.glassdoor.com/sqll/4138/accenture-squarelogo-1581057064254.png"},
    {name: "CenturyLink",
    url: "centurylink.com",
    image: "https://www.multichannel.com/.image/t_share/MTU0MDYzODQxMjA5ODIwOTIz/centurylink-logo-400x300jpg.jpg"},
    {name: "Cox",
    url: "cox.com",
    image:"https://upload.wikimedia.org/wikipedia/commons/0/03/Cox_Communications_Logo.svg"},
    {name: "Spectrum",
    url: "spectrum.com",
    image:"https://cdn.freebiesupply.com/logos/large/2x/spectrum-3-logo-png-transparent.png"},
    {name: "Newegg",
    url: "newegg.com",
    image:"https://store-images.s-microsoft.com/image/apps.31835.9007199266244178.cc988b41-654c-4902-82d2-b4981b15cb61.dd2f18bf-1d3e-4700-bf6c-bd23e60ac94c?mode=scale&q=90&h=200&w=200&background=%231f5497"},
    {name: "Forever 21",
    url: "forever21.com", 
    image:"https://res.cloudinary.com/westfielddg/image/upload/westfield-media/us/retailer/logos/wc5rnmluypbnnhsehgnj.png"},
    {name: "boohoo",
    url: "boohoo.com",
    image: "https://www.directorstalk.net/wp-content/uploads/2016/09/boohoo-plc.png"},
    {name: "Fashion Nova",
    url: "fashionnova.com",
    image: "https://i.ya-webdesign.com/images/fashion-nova-logo-png-16.png"},
    {name: "Shein",
    url: "us.shein.com",
    image:"https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/77/d2/77/77d2777c-cc2b-9b64-dcf0-fb7be7c709cb/AppIcon-0-0-1x_U007emarketing-0-0-0-7-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/246x0w.png"},
    {name: "PacSun",
    url: "pacsun.com",
    image: "https://pluspng.com/img-png/pacsun-png-pacsun-logo-450.jpg"},
    {name: "ASOS",
    url: "asos.com",
    image:"https://d1bntizjlw65va.cloudfront.net/f8e7ff22b8189a2626692545b4584bf738a6b9ad.jpg"},
    {name: "Rue21",
    url: "rue21.com",
    image: "https://i.pinimg.com/originals/f3/56/dc/f356dc233cf344efa96499b322d437c3.png"},
    {name: "Modcloth",
    url: "modcloth.com",
    image:"https://www.logolynx.com/images/logolynx/49/4912dd5d977bf7009d98a94b44f43648.png"},
    {name: "Lulus",
    url: "lulus.com",
    image:"https://d1bntizjlw65va.cloudfront.net/44cc83481d8b8b7786625e0d3b75217742977ccc.jpg"},
    {name: "Zaful",
    url: "zaful.com",
    image: "https://img.apksum.com/53/com.zaful/5.5.0/icon.png"},
    {name: "NastyGal",
    url: "nastygal.com",
    image: "https://media.glassdoor.com/sqll/346811/nasty-gal-squarelogo.png"},
    {name: "Poshmark",
    url: "poshmark.com",
    image:"https://d2gjrq7hs8he14.cloudfront.net/webpack4/pm-logo-e91dbf6c3bd90ec113f01f7f3b4d2f43.png"},
    {name: "StitchFix",
    url: "stitchfix.com",
    image: "https://i.pinimg.com/280x280_RS/87/e7/e0/87e7e0cef7d97186bf1d694f0b2cd9ae.jpg"},
    {name: "ThredUP",
    url: "thredup.com",
    image:"https://images.ctfassets.net/0tzzxvh315e4/40j5ZsscUTAlvUVTqinsnA/0a2b1db21a89e9c96196f5e3182d9e84/sv19_honorees_450px_r3_brands_thredup.jpg"},
    {name: "PrettyLittleThing",
    url: "prettylittlething.us",
    image:"https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/4b/95/1a/4b951a7d-fd21-4959-a47e-963930f158fd/AppIcon-0-0-1x_U007emarketing-0-0-0-10-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/246x0w.png"},
    {name: "Francesca’s",
    url: "francescas.com",
    image:"https://www.visitbrookfield.com/wp-content/sabai/File/files/l_22e9bd88376662415fa8d3cce36ecd04.jpg"},
    {name: "Overstock",
    url: "overstock.com",
    image:"https://media.glassdoor.com/sqll/14907/overstock-com-squarelogo-1529535998697.png"},
    {name: "World Market",
    url: "worldmarket.com",
    image: "https://assets.simon.com/tenantlogos/11039.png"},
    {name: "Anthropologie",
    url: "anthropologie.com",
    image:"https://stylinityprofiles.blob.core.windows.net/52a5bbfb-90c2-4566-891e-5b5db298a741/52a5bbfb-90c2-4566-891e-5b5db298a741-a.png"},
    {name: "Behance",
    url: "https://www.behance.net/",
    image:"https://seeklogo.com/images/B/behance-network-gallery-logo-F3327DB8A6-seeklogo.com.png"},
    {name: "Trello",
    url: "https://trello.com/",
    image:"https://is5-ssl.mzstatic.com/image/thumb/Purple114/v4/12/bd/2f/12bd2fc9-414f-1bd8-ace5-7730fdc86e4a/electron.png/246x0w.png"},
    {name: "Github",
    url: "github.com",
    image:"https://tr3.cbsistatic.com/hub/i/r/2019/06/19/7af60099-f5e9-4273-a29b-cc5ef9332607/resize/1200x/557688f8f4918d630e420ab4124f670b/githero.jpg"},
    {name: "FedEx",
    url: "fedex.com",
    image: "https://i.dlpng.com/static/png/6448240_preview.png"},
    {name: "UPS",
    url: "ups.com",
    image:"https://www.pngpix.com/wp-content/uploads/2016/07/PNGPIX-COM-UPS-Logo-PNG-Transparent-500x571.png"},
    {name: "Vercel",
    url: "vercel.com",
    image: "https://assets.vercel.com/image/upload/v1588805858/repositories/vercel/logo.png"},
    {name: "FireLink Tech",
    url: "firelinktech.com",
    image: "https://www.firelinktech.com/customLogo.png"},
    {name: "HEMAA",
    url: "hemaalliance.com",
    image:"https://upload.wikimedia.org/wikipedia/en/thumb/1/18/HEMA_Alliance_logo.jpg/220px-HEMA_Alliance_logo.jpg"},
    {name: "PCPartPicker",
    url: "pcpartpicker.com",
    image: "https://pbs.twimg.com/profile_images/567364440341762052/pBke8aj5_400x400.png"},
    {name: "BuildMyPC",
    url: "buildmypc.net",
    image: "https://ik.imagekit.io/bmpc/assets/images/slider/1.jpg"},
    {name: "Vox",
    url: "vox.com",
    image:"https://cdn.vox-cdn.com/thumbor/REwdWM3Wwgn4IaYEi5AekzezGaM=/0x0:1920x1080/1200x800/filters:focal(807x387:1113x693)/cdn.vox-cdn.com/uploads/chorus_image/image/66622762/voxlogo.0.jpg"},
    {name: "VICE",
    url: "vice.com",
    image: "https://channels.roku.com/images/9d3e2d5558134bb2bc1673ec377ed751-hd.png"},
    {name: "HBO",
    url: "hbo.com",
    image: "https://www.decalsplanet.com/img_b/vinyl-decal-sticker-1845.jpg"},
    {name: "GUCCI",
    url: "gucci.com",
    image:"https://www.talkwalker.com/Pictures/Brands/small/csm-talkwalker-gucci-6fc50823aa..jpg"},
    {name: "Pandora",
    url: "pandora.com",
    image:"https://pluspng.com/img-png/pandora-png-other-resolutions-240-240-pixels-480-480-pixels-768.png"},
    {name: "Discover",
    url: "discover.com",
    image: "https://www.discover.com/company/images/newsroom/media-downloads/discover.png"},
    {name: "American Express",
    url: "americanexpress.com",
    image:"https://about.americanexpress.com/sites/americanexpress.newshq.businesswire.com/files/logo/image/AXP_BlueBoxLogo_EXTRALARGEscale_RGB_DIGITAL_1600x1600.png"},
    {name: "Visa",
    url: "visa.com",
    image: "https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/363_Visa_Credit_Card_logo-512.png"},
    {name: "Mastercard",
    url: "mastercard.com",
    image:"https://brand.mastercard.com/content/dam/mccom/brandcenter/thumbnails/mastercard_vrt_rev_92px_2x.png"},
    {name: "NASA",
    url: "nasa.gov",
    image: "https://www.nasa.gov/sites/default/files/thumbnails/image/nasa-logo-web-rgb.png"},
    {name: "CrunchyRoll",
    url: "crunchyroll.com",
    image:"https://upload.wikimedia.org/wikipedia/en/thumb/f/f6/Crunchyroll_Logo.svg/1200px-Crunchyroll_Logo.svg.png"},
    {name: "Lockheed Martin",
    url: "lockheedmartin.com",
    image:"https://gateway.foresee.com/sites/lockheed-martin/production/trigger/LM_mobile.jpg"},
    {name: "Raytheon",
    url: "rtx.com",
    image: "https://dwglogo.com/wp-content/uploads/2016/03/Raytheon_logo_02.png"},
    {name: "G2A",
    url: "g2a.com",
    image: "https://www.pngkit.com/png/full/241-2410252_g2a-pay-g2a-logo.png"},
    {name: "US Army",
    url: "army.mil",
    image: "https://cdn.freebiesupply.com/logos/large/2x/us-army-logo-png-transparent.png"},
    {name: "Go Army",
    url: "goarmy.com",
    image: "https://cdn.freebiesupply.com/logos/large/2x/us-army-logo-png-transparent.png"},
    {name: "US Navy",
    url: "navy.com",
    image:"https://images-na.ssl-images-amazon.com/images/I/71-z%2B0aZUJL._AC_SL1001_.jpg"},
    {name: "US Marines",
    url: "marines.com",
    image: "https://rugratsva.com/wp-content/uploads/2014/03/FLAG-USA-29-1000-1200x900.jpg"},
    {name: "US Air Force",
    url: "airforce.com",
    image: "https://i.ebayimg.com/images/g/BHYAAOSwr0ReDHKw/s-l640.jpg"},
    {name: "US Coast Guard",
    url: "uscg.mil",
    image:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Seal_of_the_United_States_Coast_Guard.svg/1200px-Seal_of_the_United_States_Coast_Guard.svg.png"},
    {name: "Zoom",
    url: "zoom.com",
    image:"https://marketplace.mypurecloud.com/850d2640-3516-4972-a76e-3cddfbd3c188/applogo_5de93277.png"},
    {name: "Urban Dictionary",
    url: "urbandictionary.com",
    image:"https://slack-files2.s3-us-west-2.amazonaws.com/avatars/2018-01-11/297387706245_85899a44216ce1604c93_512.jpg"},
    {name: "JetPunk",
    url: "jetpunk.com",
    image: "https://www.jetpunk.com/img/fish.svg"},
    {name: "Addicting Games",
    url: "addictinggames.com",
    image: "https://www.userlogos.org/files/logos/macleod.mac/addictinggames.1.u.png"},
    {name: "Armor Games",
    url: "armorgames.com",
    image: "https://userlogos.org/files/logos/zigzag/armorgames.png"},
    {name: "Kongregate",
    url: "kongregate.com",
    image: "https://upload.wikimedia.org/wikipedia/en/5/55/Kongregate_logo.jpg"},
    {name: "Buzzport",
    url: "buzzport.gatech.edu",
    image:"https://seeklogo.com/images/G/georgia-tech-yellowjackets-logo-909E576F48-seeklogo.com.png"},
    {name: "Bape",
    url: "bapeonline.com",
    image: "https://projectdestroyer.com/wp-content/uploads/2020/01/bape-logo-png-2.png"},
    {name: "Lush",
    url: "lushusa.com",
    image: "https://pbs.twimg.com/profile_images/1120784179182989312/uucySY3-.png"},
    {name: "Kith",
    url: "kith.com",
    image: "https://pbs.twimg.com/profile_images/805792823224242176/qMokS064.jpg"},
    {name: "Deloitte",
    url: "deloitte.com",
    image: "https://www2.deloitte.com/content/dam/Deloitte/us/Images/promo_images/deloitte/us-deloitte-logo.jpg"},
    {name: "Procter & Gamble",
    url: "pg.com",
    image:"https://upload.wikimedia.org/wikipedia/en/thumb/8/85/Procter_%26_Gamble_logo.svg/1200px-Procter_%26_Gamble_logo.svg.png"},
    {name: "Johnson & Johnson",
    url: "jnj.com",
    image:"https://pbs.twimg.com/profile_images/1101560913885315074/9KHsZD7M_400x400.png"},
]